version: '2'
services:
  dnscrypt_x86_64:
    build:
      context: .
      dockerfile: dockerfile.x86_64
    ports:
      - "53:53"
      - "53:53/udp"
  dnscrypt_armhf:
    build:
      context: .
      dockerfile: dockerfile.armhf
    ports:
      - "53:53"
      - "53:53/udp"